### ISSUE TITLE
Review PR `set_contract_storage()`

### ISSUE THREAD

**Issue by arturoBeccar** [CoinFabrik/on-ink-integration-tests#115]
Review the PR on `set_contract_storage()`
https://github.com/paritytech/ink/pull/1961

In particular, review these failing tests:

```console
failures:

---- lazy::mapping::tests::fallible_storage_fails_gracefully_for_overgrown_data stdout ----
thread 'lazy::mapping::tests::fallible_storage_fails_gracefully_for_overgrown_data' panicked at /mnt/dev-disk/OnInk/on-ink_ink_set-contract-storage/crates/env/src/engine/off_chain/impls.rs:202:13:
Value too large to be stored in contract storage, maximum size is 16380 bytes
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- lazy::mapping::tests::fallible_storage_works_for_fitting_data stdout ----
thread 'lazy::mapping::tests::fallible_storage_works_for_fitting_data' panicked at /mnt/dev-disk/OnInk/on-ink_ink_set-contract-storage/crates/env/src/engine/off_chain/impls.rs:202:13:
Value too large to be stored in contract storage, maximum size is 16380 bytes

---- lazy::tests::fallible_storage_works_for_fitting_data stdout ----
thread 'lazy::tests::fallible_storage_works_for_fitting_data' panicked at /mnt/dev-disk/OnInk/on-ink_ink_set-contract-storage/crates/env/src/engine/off_chain/impls.rs:202:13:
Value too large to be stored in contract storage, maximum size is 16380 bytes

---- lazy::tests::fallible_storage_fails_gracefully_for_overgrown_data stdout ----
thread 'lazy::tests::fallible_storage_fails_gracefully_for_overgrown_data' panicked at /mnt/dev-disk/OnInk/on-ink_ink_set-contract-storage/crates/env/src/engine/off_chain/impls.rs:202:13:
Value too large to be stored in contract storage, maximum size is 16380 bytes


failures:
	lazy::mapping::tests::fallible_storage_fails_gracefully_for_overgrown_data
	lazy::mapping::tests::fallible_storage_works_for_fitting_data
	lazy::tests::fallible_storage_fails_gracefully_for_overgrown_data
	lazy::tests::fallible_storage_works_for_fitting_data

```

**Comment by XianPaz** [comment]
reviewed by @Helios-vmg
